export const CATEGORY_OPTIONS = [
  "Entertainment & Gossip",
  "Communities",
  "Music",
  "Food & Cooking",
  "Tech & Innovation",
  "Travel & Tourism",
  "Arts & Culture",
  "Adult & X-Rated",
  "Web3 & Finance",
  "Business & Money",
  "Sports & Fitness",
  "Politics",
  "Podcasts & Newsletters",
  "Comedy & Skits",
  "Lifestyle & Culture",
  "Dating & Marriage",
  "News & Opinions",
  "Movie & Drama",
  "Gaming & Esports",
  "Fashion & Beauty",
  "Health & Wellness",
  "Education & Learning",
  "Automotive",
  "Real Estate & Property",
  "Parenting & Family",
  "Pets & Animals",
  "DIY & Crafts",
  "Photography & Videography",
  "Science & Nature",
  "Books & Literature",
  "Religion & Spirituality",
  "Charity & Social Cause",
];
